# coding=utf-8
#

# pylint: skip-file

"""
 Copyright (c) 2019, Alexander Magola. All rights reserved.
 license: BSD 3-Clause License, see LICENSE for more details.
"""

import zm.assist as assist
import zm.wscriptimpl as wscriptimpl

# these variables are mandatory ('/' are converted automatically)
top = assist.BUILDROOT
out = assist.BUILDOUT

# mostly for WAF 'dist' command
APPNAME = assist.PROJECT_NAME
VERSION = assist.PROJECT_VERSION

def options(opt):
    wscriptimpl.options(opt)

def init(ctx):

    wscriptimpl.init(ctx)

    # It's necessary to do it here
    from waflib.Build import BuildContext, CleanContext, InstallContext, UninstallContext
    buildtype = assist.buildConfHandler.selectedBuildType
    for c in (BuildContext, CleanContext, InstallContext, UninstallContext):
        class CtxClass(c):
            variant = buildtype

def configure(conf):
    wscriptimpl.configure(conf)

def build(bld):
    wscriptimpl.build(bld)