# coding=utf-8
#

# pylint: skip-file

"""
 Copyright (c) 2019, Alexander Magola. All rights reserved.
 license: BSD 3-Clause License, see LICENSE for more details.

 This module is entry WAF wscript file that is copied from zenmake.

 Do not commit this to version control.
"""

from zm.wscriptimpl import *
